// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function Stack(props) {
  var __className = props.className;
  var className = __className !== undefined ? __className : "";
  var defaultClassName = [
    "flex",
    "flex-col",
    "items-stretch",
    "gap-4"
  ];
  var partial_arg = Belt_Array.concat(defaultClassName, className.split(" "));
  var appClassName = function (param) {
    return Belt_Array.joinWith(partial_arg, " ", param);
  };
  return JsxRuntime.jsx("div", {
              children: props.children,
              className: Curry._1(appClassName, (function (a) {
                      return a;
                    }))
            });
}

var make = Stack;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
