// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function View(props) {
  var user = props.user;
  var onClick = function (param) {
    console.log("Hello World");
  };
  var hobbies = user.hobbies;
  var hobbies$1 = hobbies !== undefined ? hobbies : [];
  var formattedHobbies = Belt_Array.map(hobbies$1, (function (hobby) {
          return hobby.toUpperCase();
        }));
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("p", {
                      children: "Hello World"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("p", {
                              children: user.name
                            }),
                        JsxRuntime.jsx("p", {
                              children: user.age.toString()
                            })
                      ]
                    }),
                JsxRuntime.jsx("button", {
                      children: "Click me",
                      onClick: onClick
                    }),
                JsxRuntime.jsx("div", {
                      children: Belt_Array.map(formattedHobbies, (function (hobby) {
                              return JsxRuntime.jsx("p", {
                                          children: hobby
                                        });
                            }))
                    })
              ]
            });
}

var make = View;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
